#!/usr/bin/env bash
# Displays numbers 1 to 10, printing "Hi" right after the number 9
i=1
while [ "$i" -le 10 ]; do
	if [ "$i" -lt 9 ]; then
		echo "$i"
	elif [ "$i" -eq 9 ]; then
		echo "$i"
		echo Hi
	else
		echo "$i"
	fi
	i=$((i + 1))
done
