#!/usr/bin/env bash
# Displays numbers 1 to 10; "bad luck" for 4, "good luck" for 8
i=1
while [ "$i" -le 10 ]; do
	if [ "$i" -eq 4 ]; then
		echo "bad luck"
	elif [ "$i" -eq 8 ]; then
		echo "good luck"
	else
		echo "$i"
	fi
	i=$((i + 1))
done

