#!/usr/bin/env bash
# Displays numbers 1 to 20 with superstitions after 4, 9, and 17
for i in {1..10}; do
   if [ "$i" -eq 4 ]; then
      echo "bad luck"
   elif [ "$i" -eq 8 ]; then
      echo "good luck"
   else
      echo "$i"
   fi
done 
