#!/usr/bin/env bash
# This scipts prints from 1 to 20 with superstitous notes after 4,9 and 17
for i in {1..20}; do
   echo "$i"
   case "$i" in 
      4)
         echo "bad luck from China"
         ;;
      9)
         echo "bad luck from Japan"
         ;;
      17)
         echo "bad luck from Italy"
         ;;
   esac
done
