#!/bin/bash
echo "$WATER $STIR" | awk '
BEGIN{
w="water."; s="stir."; b="bestchol";
for(i=1;i<=length(w);i++) wmap[substr(w,i,1)]=i-1;
for(i=1;i<=length(s);i++) smap[substr(s,i,1)]=i-1;
}
{
n1=0;n2=0;

for(i=1;i<=length($1);i++)
n1=n1*5 + wmap[substr($1,i,1)];

for(i=1;i<=length($2);i++)
n2=n2*5 + smap[substr($2,i,1)];

n=n1+n2;

r="";
while(n>0){
r=substr(b,(n%9)+1,1) r;
n=int(n/9);
}

print r;
}'
